import {
  BLIND_SELECTION_CONTROLLER_ID,
  BLIND_SELECTION_PANEL_ID,
  BLIND_SELECTION_ROW_IDS,
  BLIND_SELECTION_SELECTED_ID,
  blindSelectedCardLeaveRoutine,
  cancelBlindSelectionRoutine,
  confirmBlindSelectionRoutine,
} from '../routines/blindSelection.js';
import type { Widget } from '../types/vtt.js';
import { label, widget } from './factory.js';

const rowY = [72, 208, 344];

export function createBlindSelectionWidgets(mainBackAsset: string): Widget[] {
  return [
    widget(BLIND_SELECTION_CONTROLLER_ID, 'basic', {
      x: 0,
      y: 0,
      width: 1,
      height: 1,
      display: false,
      movable: false,
      active: false,
      sourceSeat: '',
      sourcePlayer: '',
      phase: 'idle',
    }),
    widget(BLIND_SELECTION_PANEL_ID, 'basic', {
      x: 500,
      y: 245,
      width: 800,
      height: 515,
      display: false,
      movable: true,
      layer: 70,
      color: '#182923f2',
      css: {
        border: '4px double #c2a05f',
        borderRadius: '13px',
        boxShadow: '0 10px 28px #000c',
        transformOrigin: 'top left',
      },
    }),
    label('blind-selection-title', '暗牌选择台', 18, 12, 764, BLIND_SELECTION_PANEL_ID, {
      height: 30,
      layer: 72,
      css: {
        color: '#f6dfad',
        fontSize: '19px',
        textAlign: 'center',
        fontWeight: '700',
        textShadow: '0 2px 3px #000',
      },
    }),
    label(
      'blind-selection-instruction',
      '只能看到约定手牌背面；将一张牌背拖入右侧选择槽',
      18,
      42,
      610,
      BLIND_SELECTION_PANEL_ID,
      {
        height: 24,
        layer: 72,
        css: {
          color: '#c8d9cf',
          fontSize: '12px',
          textAlign: 'left',
        },
      },
    ),
    ...BLIND_SELECTION_ROW_IDS.map((id, index) =>
      widget(id, 'holder', {
        parent: BLIND_SELECTION_PANEL_ID,
        x: 18,
        y: rowY[index],
        width: 610,
        height: 126,
        text: '',
        movable: false,
        layer: 71,
        dropTarget: { type: 'card' },
        alignChildren: true,
        preventPiles: true,
        stackOffsetX: 45,
        stackOffsetY: 0,
        dropOffsetX: 3,
        dropOffsetY: 0,
        onEnter: {
          activeFace: 0,
          owner: null,
          clickable: false,
          movable: true,
          blindSelected: false,
        },
        color: '#112019d9',
        css: {
          border: '1px dashed #6e8f7d',
          borderRadius: '8px',
          backgroundImage: 'linear-gradient(90deg,#ffffff05,#00000018)',
        },
      }),
    ),
    label('blind-selection-selected-title', '已选择', 646, 89, 136, BLIND_SELECTION_PANEL_ID, {
      height: 25,
      layer: 72,
      css: {
        color: '#f0d898',
        fontSize: '14px',
        textAlign: 'center',
        fontWeight: '700',
      },
    }),
    widget(BLIND_SELECTION_SELECTED_ID, 'holder', {
      parent: BLIND_SELECTION_PANEL_ID,
      x: 659,
      y: 120,
      width: 110,
      height: 154,
      text: '',
      movable: false,
      layer: 72,
      dropTarget: { type: 'card' },
      dropLimit: 1,
      alignChildren: true,
      preventPiles: true,
      dropOffsetX: 10,
      dropOffsetY: 14,
      stackOffsetX: 0,
      stackOffsetY: 0,
      image: mainBackAsset,
      bgImageOpacity: 0.2,
      onEnter: {
        activeFace: 0,
        owner: null,
        clickable: false,
        movable: false,
        blindSelected: true,
      },
      onLeave: {
        activeFace: 0,
        owner: null,
        clickable: true,
        movable: true,
        blindSourceSeat: null,
        blindSourcePlayer: null,
        blindSelected: false,
      },
      leaveRoutine: blindSelectedCardLeaveRoutine,
      color: '#281c18d9',
      css: {
        border: '3px solid #c2a05f',
        borderRadius: '10px',
        boxShadow: 'inset 0 0 14px #0009',
      },
    }),
    widget('blind-selection-confirm', 'button', {
      parent: BLIND_SELECTION_PANEL_ID,
      x: 646,
      y: 298,
      width: 136,
      height: 42,
      text: '收回其余',
      movable: false,
      layer: 72,
      color: '#2f5b49',
      css: {
        color: '#f1e1b7',
        fontSize: '14px',
        fontWeight: '700',
        border: '1px solid #86aa91',
        borderRadius: '7px',
      },
      clickRoutine: confirmBlindSelectionRoutine,
    }),
    widget('blind-selection-cancel', 'button', {
      parent: BLIND_SELECTION_PANEL_ID,
      x: 646,
      y: 350,
      width: 136,
      height: 38,
      text: '取消并恢复',
      movable: false,
      layer: 72,
      color: '#67302b',
      css: {
        color: '#ffd6c7',
        fontSize: '12px',
        border: '1px solid #a45f53',
        borderRadius: '7px',
      },
      clickRoutine: cancelBlindSelectionRoutine,
    }),
    label('blind-selection-status', '等待目标玩家展开手牌', 640, 407, 145, BLIND_SELECTION_PANEL_ID, {
      height: 80,
      layer: 72,
      css: {
        color: '#d7d7ca',
        fontSize: '11px',
        textAlign: 'center',
        lineHeight: '1.35',
        whiteSpace: 'normal',
      },
    }),
  ];
}
