import { PLAYER_MODULE_STAGING_POSITIONS } from '../layouts/playerModuleStaging.js';
import {
  advancePlayPhaseRoutine,
  createSetPlayPhaseRoutine,
} from '../routines/playPhaseMarker.js';
import { createLeaveSeatRoutine, createSafeSeatClickRoutine } from '../routines/seatSafety.js';
import type { Widget } from '../types/vtt.js';
import { freeZone, label, widget } from './factory.js';

const seatCss = {
  background: 'linear-gradient(180deg,#28483e 0%,#18342c 100%)',
  backgroundColor: '#1b352d',
  color: '#f5e4b6',
  fontSize: '13px',
  fontWeight: '700',
  textAlign: 'center',
  lineHeight: '26px',
  border: '2px solid var(--color)',
  borderRadius: '7px',
  boxShadow: 'inset 0 1px 0 #ffffff14,0 2px 5px #0007',
  padding: '0 6px',
  overflow: 'hidden',
  whiteSpace: 'nowrap',
  textOverflow: 'ellipsis',
  cursor: 'pointer',
};

const playPhaseButtonCss = {
  fontSize: '11px',
  color: '#ffe9b0',
  borderRadius: '6px',
  border: '1px solid #c9a24b',
  boxShadow: 'inset 0 1px 0 #ffffff10',
  fontWeight: '700',
};

export function createPlayerModule(index: number): Widget[] {
  const n = index + 1;
  const moduleId = `player-module-${n}`;
  const seatId = `seat-${n}`;
  const playerLabelId = `player-label-${n}`;
  const faceDownId = `private-zone-${n}`;
  const bounds = PLAYER_MODULE_STAGING_POSITIONS[n] || { x: 685, y: 90, width: 430, height: 260 };
  const initialDisplay = n <= 4;

  return [
    widget(moduleId, 'basic', {
      ...bounds,
      display: initialDisplay,
      movable: true,
      color: '#102a23e8',
      layer: n > 4 ? 10 : 0,
      css: {
        background: 'linear-gradient(180deg,#183a30e8 0%,#102820ee 100%)',
        border: '2px solid #8a7042',
        borderRadius: '11px',
        boxShadow: '0 5px 14px #0009,inset 0 1px 0 #ffffff0b',
        transformOrigin: 'top left',
      },
    }),
    widget(`play-phase-frame-${n}`, 'basic', {
      parent: moduleId,
      x: 0,
      y: 0,
      width: 430,
      height: 260,
      display: false,
      movable: false,
      layer: 1,
      color: '#0000',
      css: {
        border: '3px solid #e8b84a',
        borderRadius: '11px',
        boxShadow: '0 0 14px #e8b84a66',
        pointerEvents: 'none',
      },
    }),
    widget(`player-header-${n}`, 'basic', {
      parent: moduleId,
      x: 7,
      y: 7,
      width: 416,
      height: 36,
      movable: false,
      layer: 0,
      color: '#0d211be8',
      css: {
        border: '1px solid #526b5d',
        borderRadius: '8px',
        boxShadow: 'inset 0 1px 0 #ffffff0c',
        pointerEvents: 'none',
      },
    }),
    widget(seatId, 'seat', {
      parent: moduleId,
      x: 10,
      y: 9,
      width: 120,
      height: 30,
      layer: 3,
      index,
      displayEmpty: '入座',
      display: 'playerName',
      tableNickname: '',
      color: '#8c7043',
      colorEmpty: '#8c7043',
      clickRoutine: createSafeSeatClickRoutine(seatId, playerLabelId),
      css: seatCss,
      playerChangeRoutine: [{ func: 'CALL', widget: 'table-controller', routine: 'updateHandCountsRoutine' }],
    }),
    widget(`leave-seat-${n}`, 'button', {
      parent: moduleId,
      x: 134,
      y: 9,
      width: 42,
      height: 30,
      layer: 3,
      text: '离座',
      color: '#512923',
      css: {
        fontSize: '11px',
        color: '#f4cdbb',
        borderRadius: '7px',
        border: '1px solid #8f5148',
        boxShadow: 'inset 0 1px 0 #ffffff0d',
      },
      clickRoutine: createLeaveSeatRoutine(seatId),
    }),
    widget(`set-play-phase-${n}`, 'button', {
      parent: moduleId,
      x: 180,
      y: 9,
      width: 44,
      height: 30,
      layer: 3,
      text: '出牌',
      color: '#4a3a18',
      css: playPhaseButtonCss,
      clickRoutine: createSetPlayPhaseRoutine(n),
    }),
    widget(`advance-play-phase-${n}`, 'button', {
      parent: moduleId,
      x: 228,
      y: 9,
      width: 56,
      height: 30,
      layer: 3,
      text: '下一位',
      color: '#3a3420',
      css: playPhaseButtonCss,
      clickRoutine: advancePlayPhaseRoutine,
    }),
    label(`hand-count-title-${n}`, '🃏', 288, 12, 28, moduleId, {
      height: 22,
      css: {
        color: '#d8c89f',
        fontSize: '12px',
        textAlign: 'center',
        fontWeight: '600',
      },
    }),
    widget(`hand-count-${n}`, 'label', {
      parent: moduleId,
      x: 320,
      y: 9,
      width: 78,
      height: 30,
      text: 0,
      movable: false,
      layer: 3,
      css: {
        background: '#171820',
        color: '#f5dda3',
        fontSize: '16px',
        textAlign: 'center',
        fontWeight: '700',
        lineHeight: '28px',
        border: '1px solid #9b804e',
        borderRadius: '7px',
        boxShadow: 'inset 0 1px 5px #0008',
      },
    }),
    widget(`play-phase-badge-${n}`, 'label', {
      parent: moduleId,
      x: 12,
      y: 46,
      width: 72,
      height: 20,
      text: '出牌中',
      display: false,
      movable: false,
      layer: 4,
      css: {
        background: '#5c4010ee',
        color: '#ffe7a0',
        fontSize: '12px',
        lineHeight: '18px',
        textAlign: 'center',
        fontWeight: '700',
        border: '1px solid #e8b84a',
        borderRadius: '6px',
        boxShadow: '0 1px 6px #0008',
        pointerEvents: 'none',
      },
    }),
    freeZone(
      `public-zone-${n}`,
      '◎ 对外展示区\n武将 · 体力 · 装备 · 判定 · 附加牌',
      10,
      50,
      288,
      190,
      moduleId,
      {
        color: '#173b31c9',
        textColor: '#d8c89f',
        css: {
          border: '1px solid #668675',
          borderRadius: '9px',
          boxShadow: 'inset 0 0 16px #0004',
        },
      },
    ),
    widget(`private-backdrop-${n}`, 'basic', {
      parent: moduleId,
      x: 306,
      y: 50,
      width: 114,
      height: 184,
      movable: false,
      color: '#12121acc',
      css: {
        border: '1px dashed #98779a',
        borderRadius: '9px',
        backgroundImage: 'repeating-linear-gradient(135deg,#ffffff07 0 8px,#0000 8px 16px)',
        boxShadow: 'inset 0 0 12px #0007',
      },
    }),
    label(`private-label-${n}`, '暗置牌区', 309, 55, 108, moduleId, {
      height: 22,
      css: {
        color: '#d5bad6',
        fontSize: '11px',
        textAlign: 'center',
        fontWeight: '600',
      },
    }),
    widget(faceDownId, 'holder', {
      parent: moduleId,
      x: 310,
      y: 80,
      width: 106,
      height: 126,
      text: '始终盖面\n查看请移入手牌',
      textColor: '#c7aec8aa',
      layer: 2,
      alignChildren: false,
      preventPiles: true,
      showInactiveFaceToSeat: null,
      onEnter: {
        activeFace: 0,
        clickable: false,
      },
      onLeave: {
        activeFace: 0,
        clickable: true,
        owner: null,
      },
      color: '#0000',
      css: {
        border: '1px solid #b893b9',
        borderRadius: '7px',
        boxShadow: 'inset 0 0 8px #0005',
      },
    }),
    label(playerLabelId, `${n}`, 394, 236, 24, moduleId, {
      height: 18,
      css: {
        background: '#0d1d18cc',
        color: '#c9ad70',
        fontSize: '11px',
        lineHeight: '18px',
        textAlign: 'center',
        fontWeight: '700',
        border: '1px solid #6e5a35',
        borderRadius: '9px',
        textShadow: 'none',
      },
    }),
  ];
}
